package com.empik.coupon.coupon.domain;

import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Transient;
import org.springframework.data.domain.Persistable;

import java.util.UUID;

/**
 * Base class for entities whose UUID identifiers are assigned by application code rather than
 * generated by Hibernate.
 *
 * <p>Without this, {@code JpaRepository.save()} on an entity with a non-null ID treats it as a
 * detached entity and calls {@code EntityManager.merge()}, which issues a redundant
 * {@code SELECT} to look up the (non-existent) row before inserting. Implementing
 * {@link Persistable} lets us tell Spring Data explicitly whether the entity is new, so it can
 * call {@code persist()} directly on the first save and {@code merge()} after that.
 */
@MappedSuperclass
public abstract class AbstractPersistableEntity implements Persistable<UUID> {

    @Transient
    private boolean isNew = true;

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        this.isNew = false;
    }
}
